export const municipalities: string[] = [
    "Calubian, Leyte",
    "Naval, Biliran",
]

export const navalBarangay: string[] = [
    "Agpangi",
    "Anislagan",
    "Atipolo",
    "Calumpang",
    "Capiñahan",
    "Caraycaray",
    "Catmon",
    "Haguikhikan",
    "Padre Inocentes Garcia (Poblacion)",
    "Libertad",
    "Lico",
    "Lucsoon",
    "Mabini",
    "San Pablo",
    "Santo Niño",
    "Santissimo Rosario Poblacion (Santo Rosa)",
    "Talustusan",
    "Villa Caneja",
    "Villa Consuelo",
    "Borac",
    "Cabungaan",
    "Imelda",
    "Larrazabal",
    "Libtong",
    "Padre Sergio Eamiguel",
    "Sabang"
];

export const calubianBarangay: string[] = [
    "Abanilla",
    "Anislagan",
    "Bunacan",
    "Cabalquinto",
    "Herrera (Cabalhin)",
    "Cabradilla",
    "Caneja",
    "Cantonghao",
    "Caroyocan",
    "Casiongan",
    "Cristina",
    "Dalumpines",
    "Don Luis",
    "Dulao",
    "Efe (Ul-og)",
    "Enage",
    "Espinosa",
    "Ferdinand E. Marcos",
    "Garganera",
    "Garrido",
    "Guadalupe",
    "Gutosan",
    "Igang",
    "Inalad",
    "Jubay",
    "Juson",
    "Kawayan Bogtong",
    "Kawayanan",
    "Kokoy Romualdez",
    "Labtic",
    "Laray",
    "Limite (Agas)",
    "Manuel Veloso",
    "Mahait",
    "Malobago",
    "Matagok",
    "Nierras",
    "Nipa",
    "Obispo",
    "Pagatpat",
    "Pangpang",
    "Patag",
    "Pates",
    "Pal-og",
    "Padoga",
    "Petrolio",
    "Poblacion",
    "Railes",
    "Tabla",
    "Tagharigue",
    "Tuburan",
    "Villahermosa",
    "Villalon",
    "Villanueva"
];

